// This file is auto-generated by src/scripts/generate-gitmoji.ts. Do not edit directly.

export {
  BUILTIN_PRESETS,
  type BuiltinPreset,
  GITMOJI_SPEC_DATA,
  type GitmojiSpecEntry,
  getPresetConfig,
  isBuiltinPreset,
  PRESET_CONFIGS,
} from '@release-drafter/core'
