# yaml-language-server: $schema=https://raw.githubusercontent.com/release-drafter/release-drafter/master/schema.json

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
include-commits: true
change-template: '- $CHANGE_TITLE ($CHANGE_REFERENCE) $CHANGE_AUTHORS'

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: $PREVIOUS_TAG...$NEXT_TAG

exclude-labels:
  - 'skip-changelog'
  - 'skip-release'

categories:
  - title: '💥 Breaking Changes'
    labels:
      - '💥'
  - title: '✨ Features & Improvements'
    labels:
      - '✨'
      - '🎉'
      - '🚀'
      - '🚸'
      - '📱'
      - '💫'
      - '🌐'
      - '🍱'
      - '♿️'
      - '♿'
      - '🥚'
      - '⚗️'
      - '⚗'
      - '🚩'
      - '👔'
      - '🦖'
      - '✈️'
      - '✈'
  - title: '🐛 Bug Fixes & Security'
    labels:
      - '🐛'
      - '🚑️'
      - '🚑'
      - '🩹'
      - '🔒️'
      - '🔒'
      - '🔐'
      - '🛂'
      - '🦺'
      - '🥅'
      - '🚨'
      - '✏️'
      - '✏'
      - '👽️'
      - '👽'
  - title: '⚡ Performance'
    labels:
      - '⚡️'
      - '⚡'
      - '🧵'
      - '🔍️'
      - '🔍'
  - title: '📝 Documentation'
    labels:
      - '📝'
      - '💡'
      - '📄'
      - '👥'
      - '💬'
  - title: '♻️ Code Refactoring & Style'
    labels:
      - '♻️'
      - '♻'
      - '🎨'
      - '🔥'
      - '⚰️'
      - '⚰'
      - '🏗️'
      - '🏗'
      - '🗑️'
      - '🗑'
      - '🚚'
      - '🏷️'
      - '🏷'
      - '🗃️'
      - '🗃'
      - '💄'
      - '💩'
  - title: '📦 Dependency Updates'
    labels:
      - '⬆️'
      - '⬆'
      - '⬇️'
      - '⬇'
      - '📌'
      - '➕'
      - '➖'
      - '📦️'
      - '📦'
  - title: '👷 CI/CD'
    labels:
      - '👷'
      - '💚'
      - '🔧'
      - '🔨'
      - '🧱'
      - '🧑‍💻'
      - '🙈'
      - '📈'
      - '🩺'
      - '💸'
      - '🔖'
      - '🚧'
      - '🔊'
      - '🔇'
  - title: '🧪 Tests'
    labels:
      - '✅'
      - '🧪'
      - '📸'
      - '🤡'
      - '🌱'
      - '🧐'
  - title: '⏪️ Reverts & Branches'
    labels:
      - '⏪️'
      - '⏪'
      - '🔀'
      - '🍻'

version-resolver:
  major:
    labels:
      - '💥'
  minor:
    labels:
      - '✨'
      - '🎉'
      - '🚀'
      - '🚸'
      - '📱'
      - '💫'
      - '🌐'
      - '🍱'
      - '♿️'
      - '♿'
      - '🥚'
      - '⚗️'
      - '⚗'
      - '🚩'
      - '👔'
      - '🦖'
      - '✈️'
      - '✈'
  patch:
    labels:
      - '🐛'
      - '🚑️'
      - '🚑'
      - '🩹'
      - '🔒️'
      - '🔒'
      - '🔐'
      - '🛂'
      - '🦺'
      - '🥅'
      - '🚨'
      - '✏️'
      - '✏'
      - '👽️'
      - '👽'
      - '⚡️'
      - '⚡'
      - '🧵'
      - '🔍️'
      - '🔍'
      - '📝'
      - '💡'
      - '📄'
      - '👥'
      - '💬'
      - '♻️'
      - '♻'
      - '🎨'
      - '🔥'
      - '⚰️'
      - '⚰'
      - '🏗️'
      - '🏗'
      - '🗑️'
      - '🗑'
      - '🚚'
      - '🏷️'
      - '🏷'
      - '🗃️'
      - '🗃'
      - '💄'
      - '💩'
      - '⬆️'
      - '⬆'
      - '⬇️'
      - '⬇'
      - '📌'
      - '➕'
      - '➖'
      - '📦️'
      - '📦'
      - '👷'
      - '💚'
      - '🔧'
      - '🔨'
      - '🧱'
      - '🧑‍💻'
      - '🙈'
      - '📈'
      - '🩺'
      - '💸'
      - '🔖'
      - '🚧'
      - '🔊'
      - '🔇'
      - '✅'
      - '🧪'
      - '📸'
      - '🤡'
      - '🌱'
      - '🧐'
      - '⏪️'
      - '⏪'
      - '🔀'
      - '🍻'
  default: patch

autolabeler:
  - label: '💥'
    title:
      - '/^(:boom:|💥)/'
      - '/^([a-z]+(\([^\)]+\))?!:|.*BREAKING CHANGE:?)/i'
      - '/BREAKING[ -]CHANGE/i'
    branch:
      - '/.*breaking.*/i'
    body:
      - '/BREAKING[ -]CHANGE:/i'

  - label: '✨'
    title:
      - '/^(:sparkles:|✨)/'
    branch:
      - '/^feat(\//|-)/i'
      - '/^feature(\//|-)/i'

  - label: '🎉'
    title:
      - '/^(:tada:|🎉)/'

  - label: '🚀'
    title:
      - '/^(:rocket:|🚀)/'

  - label: '🚸'
    title:
      - '/^(:children_crossing:|🚸)/'

  - label: '📱'
    title:
      - '/^(:iphone:|📱)/'

  - label: '💫'
    title:
      - '/^(:dizzy:|💫)/'

  - label: '🌐'
    title:
      - '/^(:globe_with_meridians:|🌐)/'

  - label: '🍱'
    title:
      - '/^(:bento:|🍱)/'

  - label: '♿️'
    title:
      - '/^(:wheelchair:|♿️?)/'

  - label: '🥚'
    title:
      - '/^(:egg:|🥚)/'

  - label: '⚗️'
    title:
      - '/^(:alembic:|⚗️?)/'

  - label: '🚩'
    title:
      - '/^(:triangular_flag_on_post:|🚩)/'

  - label: '👔'
    title:
      - '/^(:necktie:|👔)/'

  - label: '🦖'
    title:
      - '/^(:t-rex:|🦖)/'

  - label: '✈️'
    title:
      - '/^(:airplane:|✈️?)/'

  - label: '🐛'
    title:
      - '/^(:bug:|🐛)/'
    branch:
      - '/^fix(\//|-)/i'
      - '/^bugfix(\//|-)/i'
      - '/^hotfix(\//|-)/i'
      - '/^sec(urity)?(\//|-)/i'

  - label: '🚑️'
    title:
      - '/^(:ambulance:|🚑️?)/'

  - label: '🩹'
    title:
      - '/^(:adhesive_bandage:|🩹)/'

  - label: '🔒️'
    title:
      - '/^(:lock:|🔒️?)/'

  - label: '🔐'
    title:
      - '/^(:closed_lock_with_key:|🔐)/'

  - label: '🛂'
    title:
      - '/^(:passport_control:|🛂)/'

  - label: '🦺'
    title:
      - '/^(:safety_vest:|🦺)/'

  - label: '🥅'
    title:
      - '/^(:goal_net:|🥅)/'

  - label: '🚨'
    title:
      - '/^(:rotating_light:|🚨)/'

  - label: '✏️'
    title:
      - '/^(:pencil2:|✏️?)/'

  - label: '👽️'
    title:
      - '/^(:alien:|👽️?)/'

  - label: '⚡️'
    title:
      - '/^(:zap:|⚡️?)/'
    branch:
      - '/^perf(\//|-)/i'

  - label: '🧵'
    title:
      - '/^(:thread:|🧵)/'

  - label: '🔍️'
    title:
      - '/^(:mag:|🔍️?)/'

  - label: '📝'
    files:
      - '**/*.md'
      - 'docs/**'
    title:
      - '/^(:memo:|📝)/'
      - '/^docs?(\([^\)]+\))?:/i'
    branch:
      - '/^docs?(\//|-)/i'

  - label: '💡'
    title:
      - '/^(:bulb:|💡)/'

  - label: '📄'
    title:
      - '/^(:page_facing_up:|📄)/'

  - label: '👥'
    title:
      - '/^(:busts_in_silhouette:|👥)/'

  - label: '💬'
    title:
      - '/^(:speech_balloon:|💬)/'

  - label: '♻️'
    title:
      - '/^(:recycle:|♻️?)/'
    branch:
      - '/^refactor(\//|-)/i'
      - '/^style(\//|-)/i'

  - label: '🎨'
    title:
      - '/^(:art:|🎨)/'

  - label: '🔥'
    title:
      - '/^(:fire:|🔥)/'

  - label: '⚰️'
    title:
      - '/^(:coffin:|⚰️?)/'

  - label: '🏗️'
    title:
      - '/^(:building_construction:|🏗️?)/'

  - label: '🗑️'
    title:
      - '/^(:wastebasket:|🗑️?)/'

  - label: '🚚'
    title:
      - '/^(:truck:|🚚)/'

  - label: '🏷️'
    title:
      - '/^(:label:|🏷️?)/'

  - label: '🗃️'
    title:
      - '/^(:card_file_box:|🗃️?)/'

  - label: '💄'
    title:
      - '/^(:lipstick:|💄)/'

  - label: '💩'
    title:
      - '/^(:poop:|💩)/'

  - label: '⬆️'
    title:
      - '/^(:arrow_up:|⬆️?)/'
    branch:
      - '/^dependabot\//i'
      - '/^renovate\//i'
      - '/^deps?(\//|-)/i'

  - label: '⬇️'
    title:
      - '/^(:arrow_down:|⬇️?)/'

  - label: '📌'
    title:
      - '/^(:pushpin:|📌)/'

  - label: '➕'
    title:
      - '/^(:heavy_plus_sign:|➕)/'

  - label: '➖'
    title:
      - '/^(:heavy_minus_sign:|➖)/'

  - label: '📦️'
    title:
      - '/^(:package:|📦️?)/'

  - label: '👷'
    files:
      - '.github/**'
    title:
      - '/^(:construction_worker:|👷)/'
      - '/^(ci|build)(\([^\)]+\))?:/i'
    branch:
      - '/^ci(\//|-)/i'
      - '/^build(\//|-)/i'
      - '/^chore(\//|-)/i'

  - label: '💚'
    title:
      - '/^(:green_heart:|💚)/'

  - label: '🔧'
    title:
      - '/^(:wrench:|🔧)/'

  - label: '🔨'
    title:
      - '/^(:hammer:|🔨)/'

  - label: '🧱'
    title:
      - '/^(:bricks:|🧱)/'

  - label: '🧑‍💻'
    title:
      - '/^(:technologist:|🧑‍💻)/'

  - label: '🙈'
    title:
      - '/^(:see_no_evil:|🙈)/'

  - label: '📈'
    title:
      - '/^(:chart_with_upwards_trend:|📈)/'

  - label: '🩺'
    title:
      - '/^(:stethoscope:|🩺)/'

  - label: '💸'
    title:
      - '/^(:money_with_wings:|💸)/'

  - label: '🔖'
    title:
      - '/^(:bookmark:|🔖)/'

  - label: '🚧'
    title:
      - '/^(:construction:|🚧)/'

  - label: '🔊'
    title:
      - '/^(:loud_sound:|🔊)/'

  - label: '🔇'
    title:
      - '/^(:mute:|🔇)/'

  - label: '✅'
    title:
      - '/^(:white_check_mark:|✅)/'
    branch:
      - '/^tests?(\//|-)/i'

  - label: '🧪'
    title:
      - '/^(:test_tube:|🧪)/'

  - label: '📸'
    title:
      - '/^(:camera_flash:|📸)/'

  - label: '🤡'
    title:
      - '/^(:clown_face:|🤡)/'

  - label: '🌱'
    title:
      - '/^(:seedling:|🌱)/'

  - label: '🧐'
    title:
      - '/^(:monocle_face:|🧐)/'

  - label: '⏪️'
    title:
      - '/^(:rewind:|⏪️?)/'
    branch:
      - '/^revert(\//|-)/i'

  - label: '🔀'
    title:
      - '/^(:twisted_rightwards_arrows:|🔀)/'

  - label: '🍻'
    title:
      - '/^(:beers:|🍻)/'
