# yaml-language-server: $schema=https://raw.githubusercontent.com/release-drafter/release-drafter/master/schema.json

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
include-commits: true
change-template: '- $CHANGE_TITLE ($CHANGE_REFERENCE) $CHANGE_AUTHORS'

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: $PREVIOUS_TAG...$NEXT_TAG

exclude-labels:
  - 'skip-changelog'
  - 'skip-release'

categories:
  - title: '💥 Breaking Changes'
    labels:
      - '💥'
      - 'boom'
      - 'breaking'
      - 'breaking-change'
  - title: '✨ Features & Improvements'
    labels:
      - '✨'
      - '🎉'
      - '🚀'
      - '🚸'
      - '📱'
      - '💫'
      - '🌐'
      - '🍱'
      - '♿️'
      - '♿'
      - '🥚'
      - '⚗️'
      - '⚗'
      - '🚩'
      - '👔'
      - '🦖'
      - '✈️'
      - '✈'
      - 'sparkles'
      - 'tada'
      - 'rocket'
      - 'children-crossing'
      - 'iphone'
      - 'dizzy'
      - 'globe-with-meridians'
      - 'bento'
      - 'wheelchair'
      - 'egg'
      - 'alembic'
      - 'triangular-flag-on-post'
      - 'necktie'
      - 't-rex'
      - 'airplane'
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: '🐛 Bug Fixes & Security'
    labels:
      - '🐛'
      - '🚑️'
      - '🚑'
      - '🩹'
      - '🔒️'
      - '🔒'
      - '🔐'
      - '🛂'
      - '🦺'
      - '🥅'
      - '🚨'
      - '✏️'
      - '✏'
      - '👽️'
      - '👽'
      - 'bug'
      - 'ambulance'
      - 'adhesive-bandage'
      - 'lock'
      - 'closed-lock-with-key'
      - 'passport-control'
      - 'safety-vest'
      - 'goal-net'
      - 'rotating-light'
      - 'pencil2'
      - 'alien'
      - 'fix'
      - 'bugfix'
      - 'security'
  - title: '⚡ Performance'
    labels:
      - '⚡️'
      - '⚡'
      - '🧵'
      - '🔍️'
      - '🔍'
      - 'zap'
      - 'thread'
      - 'mag'
      - 'perf'
      - 'performance'
  - title: '📝 Documentation'
    labels:
      - '📝'
      - '💡'
      - '📄'
      - '👥'
      - '💬'
      - 'memo'
      - 'bulb'
      - 'page-facing-up'
      - 'busts-in-silhouette'
      - 'speech-balloon'
      - 'docs'
      - 'documentation'
  - title: '♻️ Code Refactoring & Style'
    labels:
      - '♻️'
      - '♻'
      - '🎨'
      - '🔥'
      - '⚰️'
      - '⚰'
      - '🏗️'
      - '🏗'
      - '🗑️'
      - '🗑'
      - '🚚'
      - '🏷️'
      - '🏷'
      - '🗃️'
      - '🗃'
      - '💄'
      - '💩'
      - 'recycle'
      - 'art'
      - 'fire'
      - 'coffin'
      - 'building-construction'
      - 'wastebasket'
      - 'truck'
      - 'label'
      - 'card-file-box'
      - 'lipstick'
      - 'poop'
      - 'refactor'
      - 'style'
  - title: '📦 Dependency Updates'
    labels:
      - '⬆️'
      - '⬆'
      - '⬇️'
      - '⬇'
      - '📌'
      - '➕'
      - '➖'
      - '📦️'
      - '📦'
      - 'arrow-up'
      - 'arrow-down'
      - 'pushpin'
      - 'heavy-plus-sign'
      - 'heavy-minus-sign'
      - 'package'
      - 'dependencies'
      - 'deps'
  - title: '👷 CI, Build & Tooling'
    labels:
      - '👷'
      - '💚'
      - '🔧'
      - '🔨'
      - '🧱'
      - '🧑‍💻'
      - '🙈'
      - '📈'
      - '🩺'
      - '💸'
      - '🔖'
      - '🚧'
      - '🔊'
      - '🔇'
      - 'construction-worker'
      - 'green-heart'
      - 'wrench'
      - 'hammer'
      - 'bricks'
      - 'technologist'
      - 'see-no-evil'
      - 'chart-with-upwards-trend'
      - 'stethoscope'
      - 'money-with-wings'
      - 'bookmark'
      - 'construction'
      - 'loud-sound'
      - 'mute'
      - 'ci'
      - 'build'
      - 'chore'
  - title: '🧪 Tests'
    labels:
      - '✅'
      - '🧪'
      - '📸'
      - '🤡'
      - '🌱'
      - '🧐'
      - 'white-check-mark'
      - 'test-tube'
      - 'camera-flash'
      - 'clown-face'
      - 'seedling'
      - 'monocle-face'
      - 'test'
  - title: '⏪️ Reverts & Branches'
    labels:
      - '⏪️'
      - '⏪'
      - '🔀'
      - '🍻'
      - 'rewind'
      - 'twisted-rightwards-arrows'
      - 'beers'
      - 'revert'

version-resolver:
  major:
    labels:
      - '💥'
      - 'boom'
      - 'breaking'
      - 'breaking-change'
  minor:
    labels:
      - '✨'
      - '🎉'
      - '🚀'
      - '🚸'
      - '📱'
      - '💫'
      - '🌐'
      - '🍱'
      - '♿️'
      - '♿'
      - '🥚'
      - '⚗️'
      - '⚗'
      - '🚩'
      - '👔'
      - '🦖'
      - '✈️'
      - '✈'
      - 'sparkles'
      - 'tada'
      - 'rocket'
      - 'children-crossing'
      - 'iphone'
      - 'dizzy'
      - 'globe-with-meridians'
      - 'bento'
      - 'wheelchair'
      - 'egg'
      - 'alembic'
      - 'triangular-flag-on-post'
      - 'necktie'
      - 't-rex'
      - 'airplane'
      - 'feature'
      - 'enhancement'
      - 'feat'
  patch:
    labels:
      - '🐛'
      - '🚑️'
      - '🚑'
      - '🩹'
      - '🔒️'
      - '🔒'
      - '🔐'
      - '🛂'
      - '🦺'
      - '🥅'
      - '🚨'
      - '✏️'
      - '✏'
      - '👽️'
      - '👽'
      - 'bug'
      - 'ambulance'
      - 'adhesive-bandage'
      - 'lock'
      - 'closed-lock-with-key'
      - 'passport-control'
      - 'safety-vest'
      - 'goal-net'
      - 'rotating-light'
      - 'pencil2'
      - 'alien'
      - 'fix'
      - 'bugfix'
      - 'security'
      - '⚡️'
      - '⚡'
      - '🧵'
      - '🔍️'
      - '🔍'
      - 'zap'
      - 'thread'
      - 'mag'
      - 'perf'
      - 'performance'
      - '📝'
      - '💡'
      - '📄'
      - '👥'
      - '💬'
      - 'memo'
      - 'bulb'
      - 'page-facing-up'
      - 'busts-in-silhouette'
      - 'speech-balloon'
      - 'docs'
      - 'documentation'
      - '♻️'
      - '♻'
      - '🎨'
      - '🔥'
      - '⚰️'
      - '⚰'
      - '🏗️'
      - '🏗'
      - '🗑️'
      - '🗑'
      - '🚚'
      - '🏷️'
      - '🏷'
      - '🗃️'
      - '🗃'
      - '💄'
      - '💩'
      - 'recycle'
      - 'art'
      - 'fire'
      - 'coffin'
      - 'building-construction'
      - 'wastebasket'
      - 'truck'
      - 'label'
      - 'card-file-box'
      - 'lipstick'
      - 'poop'
      - 'refactor'
      - 'style'
      - '⬆️'
      - '⬆'
      - '⬇️'
      - '⬇'
      - '📌'
      - '➕'
      - '➖'
      - '📦️'
      - '📦'
      - 'arrow-up'
      - 'arrow-down'
      - 'pushpin'
      - 'heavy-plus-sign'
      - 'heavy-minus-sign'
      - 'package'
      - 'dependencies'
      - 'deps'
      - '👷'
      - '💚'
      - '🔧'
      - '🔨'
      - '🧱'
      - '🧑‍💻'
      - '🙈'
      - '📈'
      - '🩺'
      - '💸'
      - '🔖'
      - '🚧'
      - '🔊'
      - '🔇'
      - 'construction-worker'
      - 'green-heart'
      - 'wrench'
      - 'hammer'
      - 'bricks'
      - 'technologist'
      - 'see-no-evil'
      - 'chart-with-upwards-trend'
      - 'stethoscope'
      - 'money-with-wings'
      - 'bookmark'
      - 'construction'
      - 'loud-sound'
      - 'mute'
      - 'ci'
      - 'build'
      - 'chore'
      - '✅'
      - '🧪'
      - '📸'
      - '🤡'
      - '🌱'
      - '🧐'
      - 'white-check-mark'
      - 'test-tube'
      - 'camera-flash'
      - 'clown-face'
      - 'seedling'
      - 'monocle-face'
      - 'test'
      - '⏪️'
      - '⏪'
      - '🔀'
      - '🍻'
      - 'rewind'
      - 'twisted-rightwards-arrows'
      - 'beers'
      - 'revert'
  default: patch

autolabeler:
  - label: 'breaking'
    title:
      - '/^([a-z]+(\([^\)]+\))?!:|.*BREAKING CHANGE:?)/i'
      - '/BREAKING[ -]CHANGE/i'
    branch:
      - '/.*breaking.*/i'
    body:
      - '/BREAKING[ -]CHANGE:/i'

  - label: '💥'
    title:
      - '/^(:boom:|💥)/'
      - '/^([a-z]+(\([^\)]+\))?!:|.*BREAKING CHANGE:?)/i'
      - '/BREAKING[ -]CHANGE/i'
    branch:
      - '/.*breaking.*/i'
    body:
      - '/BREAKING[ -]CHANGE:/i'

  - label: 'feat'
    title:
      - '/^((:sparkles:|✨|:tada:|🎉|:rocket:|🚀)\s*)?feat(ure)?(\([^\)]+\))?:/i'
    branch:
      - '/^feat(\//|-)/i'
      - '/^feature(\//|-)/i'

  - label: 'fix'
    title:
      - '/^((:bug:|🐛|:ambulance:|🚑️|🚑|:adhesive_bandage:|🩹)\s*)?(fix|bugfix|hotfix)(\([^\)]+\))?:/i'
    branch:
      - '/^fix(\//|-)/i'
      - '/^bugfix(\//|-)/i'
      - '/^hotfix(\//|-)/i'

  - label: 'security'
    title:
      - '/^((:lock:|🔒)\s*)?sec(urity)?(\([^\)]+\))?:/i'
    branch:
      - '/^sec(urity)?(\//|-)/i'

  - label: 'perf'
    title:
      - '/^((:zap:|⚡️|⚡)\s*)?perf(ormance)?(\([^\)]+\))?:/i'
    branch:
      - '/^perf(\//|-)/i'

  - label: 'docs'
    files:
      - '**/*.md'
      - 'docs/**'
    title:
      - '/^((:memo:|📝|:books:|📚|:bulb:|💡)\s*)?docs?(\([^\)]+\))?:/i'
    branch:
      - '/^docs?(\//|-)/i'

  - label: 'refactor'
    title:
      - '/^((:recycle:|♻️|♻|:art:|🎨|:fire:|🔥)\s*)?refactor(\([^\)]+\))?:/i'
    branch:
      - '/^refactor(\//|-)/i'

  - label: 'dependencies'
    title:
      - '/^((:arrow_up:|⬆️|⬆|:arrow_down:|⬇️|⬇|:package:|📦️|📦|:pushpin:|📌)\s*)?(deps?|dependencies)(\([^\)]+\))?:/i'
      - '/^chore\(deps(-[a-z0-9]+)?\):/i'
    branch:
      - '/^dependabot\//i'
      - '/^renovate\//i'
      - '/^deps?(\//|-)/i'

  - label: 'ci'
    files:
      - '.github/**'
    title:
      - '/^((:construction_worker:|👷|:green_heart:|💚)\s*)?(ci|build)(\([^\)]+\))?:/i'
    branch:
      - '/^ci(\//|-)/i'
      - '/^build(\//|-)/i'

  - label: 'chore'
    title:
      - '/^((:wrench:|🔧|:hammer:|🔨|:truck:|🚚|:wastebasket:|🗑️|🗑)\s*)?chore(\([^\)]+\))?:/i'
    branch:
      - '/^chore(\//|-)/i'

  - label: 'test'
    title:
      - '/^((:white_check_mark:|✅|:test_tube:|🧪)\s*)?tests?(\([^\)]+\))?:/i'
    branch:
      - '/^tests?(\//|-)/i'

  - label: 'revert'
    title:
      - '/^((:rewind:|⏪️|⏪)\s*)?revert(\([^\)]+\))?:/i'
    branch:
      - '/^revert(\//|-)/i'

  - label: '✨'
    title:
      - '/^(:sparkles:|✨)/'

  - label: '🎉'
    title:
      - '/^(:tada:|🎉)/'

  - label: '🚀'
    title:
      - '/^(:rocket:|🚀)/'

  - label: '🚸'
    title:
      - '/^(:children_crossing:|🚸)/'

  - label: '📱'
    title:
      - '/^(:iphone:|📱)/'

  - label: '💫'
    title:
      - '/^(:dizzy:|💫)/'

  - label: '🌐'
    title:
      - '/^(:globe_with_meridians:|🌐)/'

  - label: '🍱'
    title:
      - '/^(:bento:|🍱)/'

  - label: '♿️'
    title:
      - '/^(:wheelchair:|♿️?)/'

  - label: '🥚'
    title:
      - '/^(:egg:|🥚)/'

  - label: '⚗️'
    title:
      - '/^(:alembic:|⚗️?)/'

  - label: '🚩'
    title:
      - '/^(:triangular_flag_on_post:|🚩)/'

  - label: '👔'
    title:
      - '/^(:necktie:|👔)/'

  - label: '🦖'
    title:
      - '/^(:t-rex:|🦖)/'

  - label: '✈️'
    title:
      - '/^(:airplane:|✈️?)/'

  - label: '🐛'
    title:
      - '/^(:bug:|🐛)/'

  - label: '🚑️'
    title:
      - '/^(:ambulance:|🚑️?)/'

  - label: '🩹'
    title:
      - '/^(:adhesive_bandage:|🩹)/'

  - label: '🔒️'
    title:
      - '/^(:lock:|🔒️?)/'

  - label: '🔐'
    title:
      - '/^(:closed_lock_with_key:|🔐)/'

  - label: '🛂'
    title:
      - '/^(:passport_control:|🛂)/'

  - label: '🦺'
    title:
      - '/^(:safety_vest:|🦺)/'

  - label: '🥅'
    title:
      - '/^(:goal_net:|🥅)/'

  - label: '🚨'
    title:
      - '/^(:rotating_light:|🚨)/'

  - label: '✏️'
    title:
      - '/^(:pencil2:|✏️?)/'

  - label: '👽️'
    title:
      - '/^(:alien:|👽️?)/'

  - label: '⚡️'
    title:
      - '/^(:zap:|⚡️?)/'

  - label: '🧵'
    title:
      - '/^(:thread:|🧵)/'

  - label: '🔍️'
    title:
      - '/^(:mag:|🔍️?)/'

  - label: '📝'
    files:
      - '**/*.md'
      - 'docs/**'
    title:
      - '/^(:memo:|📝)/'

  - label: '💡'
    title:
      - '/^(:bulb:|💡)/'

  - label: '📄'
    title:
      - '/^(:page_facing_up:|📄)/'

  - label: '👥'
    title:
      - '/^(:busts_in_silhouette:|👥)/'

  - label: '💬'
    title:
      - '/^(:speech_balloon:|💬)/'

  - label: '♻️'
    title:
      - '/^(:recycle:|♻️?)/'

  - label: '🎨'
    title:
      - '/^(:art:|🎨)/'

  - label: '🔥'
    title:
      - '/^(:fire:|🔥)/'

  - label: '⚰️'
    title:
      - '/^(:coffin:|⚰️?)/'

  - label: '🏗️'
    title:
      - '/^(:building_construction:|🏗️?)/'

  - label: '🗑️'
    title:
      - '/^(:wastebasket:|🗑️?)/'

  - label: '🚚'
    title:
      - '/^(:truck:|🚚)/'

  - label: '🏷️'
    title:
      - '/^(:label:|🏷️?)/'

  - label: '🗃️'
    title:
      - '/^(:card_file_box:|🗃️?)/'

  - label: '💄'
    title:
      - '/^(:lipstick:|💄)/'

  - label: '💩'
    title:
      - '/^(:poop:|💩)/'

  - label: '⬆️'
    title:
      - '/^(:arrow_up:|⬆️?)/'

  - label: '⬇️'
    title:
      - '/^(:arrow_down:|⬇️?)/'

  - label: '📌'
    title:
      - '/^(:pushpin:|📌)/'

  - label: '➕'
    title:
      - '/^(:heavy_plus_sign:|➕)/'

  - label: '➖'
    title:
      - '/^(:heavy_minus_sign:|➖)/'

  - label: '📦️'
    title:
      - '/^(:package:|📦️?)/'

  - label: '👷'
    files:
      - '.github/**'
    title:
      - '/^(:construction_worker:|👷)/'

  - label: '💚'
    title:
      - '/^(:green_heart:|💚)/'

  - label: '🔧'
    title:
      - '/^(:wrench:|🔧)/'

  - label: '🔨'
    title:
      - '/^(:hammer:|🔨)/'

  - label: '🧱'
    title:
      - '/^(:bricks:|🧱)/'

  - label: '🧑‍💻'
    title:
      - '/^(:technologist:|🧑‍💻)/'

  - label: '🙈'
    title:
      - '/^(:see_no_evil:|🙈)/'

  - label: '📈'
    title:
      - '/^(:chart_with_upwards_trend:|📈)/'

  - label: '🩺'
    title:
      - '/^(:stethoscope:|🩺)/'

  - label: '💸'
    title:
      - '/^(:money_with_wings:|💸)/'

  - label: '🔖'
    title:
      - '/^(:bookmark:|🔖)/'

  - label: '🚧'
    title:
      - '/^(:construction:|🚧)/'

  - label: '🔊'
    title:
      - '/^(:loud_sound:|🔊)/'

  - label: '🔇'
    title:
      - '/^(:mute:|🔇)/'

  - label: '✅'
    title:
      - '/^(:white_check_mark:|✅)/'

  - label: '🧪'
    title:
      - '/^(:test_tube:|🧪)/'

  - label: '📸'
    title:
      - '/^(:camera_flash:|📸)/'

  - label: '🤡'
    title:
      - '/^(:clown_face:|🤡)/'

  - label: '🌱'
    title:
      - '/^(:seedling:|🌱)/'

  - label: '🧐'
    title:
      - '/^(:monocle_face:|🧐)/'

  - label: '⏪️'
    title:
      - '/^(:rewind:|⏪️?)/'

  - label: '🔀'
    title:
      - '/^(:twisted_rightwards_arrows:|🔀)/'

  - label: '🍻'
    title:
      - '/^(:beers:|🍻)/'
